### ISSUE TITLE
히스토리 RUD 구현

### ISSUE THREAD

**Issue by kdkdhoho** [8-Sprinters/ListyWave-back#155]
# TODO
- [x] 히스토리 조회 API 구현
- [x] 히스토리 공개/비공개 수정 API 구현
- [x] 히스토리 삭제 API 구현
