### ISSUE TITLE
백엔드 개발 서버 CI/CD 구축

### ISSUE THREAD

**Issue by kdkdhoho** [8-Sprinters/ListyWave-back#17]
# Description
- 백엔드 개발 서버 CI/CD 구축

# TODO
- [x] Fork Repository에서 CI workflow 작성하여 테스트
- [x] Fork Repository에서 CD workflow 작성하여 테스트
- [x] 작성한 두 Workflow를 Origin Repositor에 반영

# Reference
- 

# 관련 Issue
-
