### ISSUE TITLE
fix: 탈퇴한 회원과 관련된 데이터가 보이는 문제를 해결한다

### ISSUE THREAD

**Issue by kdkdhoho** [8-Sprinters/ListyWave-back#210]
# TODO
- [x] 사용자 검색 확인
- [x] 리스트 상세 조회 확인
- [x] 피드 리스트 조회 확인
  - [x] 콜라보레이터 리스트
- [x] 댓글&답글 확인
- [x] 회원탈퇴하면 콜렉트했던 리스트의 콜렉트 수가 감소하는지 확인
