### ISSUE TITLE
collaborator 테이블에 ownerId가 포함되지 않도록 구현

### ISSUE THREAD

**Issue by kdkdhoho** [8-Sprinters/ListyWave-back#236]
# Description
리스트 수정 시, 생길 수 있는 동시성 문제를 해결하기 위해 여러 테스트를 진행 중입니다.
하지만 collaborator 테이블에 ownerId가 포함되어, 리스트 수정 로직이 굉장히 복잡해지고 많은 버그가 생겨 이를 개선합니다.

# TODO
- [x] 리스트 생성 시, collaborators에 본인을 포함하지 않습니다.
- [x] 피드에서 콜라보 리스트 조회 시, 본인이 작성한 콜라보 리스트 및 콜라보레이터로 포함된 리스트를 모두 응답합니다.
- [x] 리스트 수정 시, 요청 데이터의 collaboratorIds 필드에 더 이상 ownerId를 포함하지 않습니다.
  - [x] 수정 단계에서 collaborator를 저장할 때에도 ownerId를 포함하지 않습니다.
