### ISSUE TITLE
운영 서버 구축

### ISSUE THREAD

**Issue by kdkdhoho** [8-Sprinters/ListyWave-back#251]
# TODO
- [x] 운영 서버 구축
  - [x] prod 브랜치 만들기
  - [x] CI workflow에 prod 브랜치 추가하기
  - [x] Prod용 데이터베이스 구축하기
  - [x] Prod용 CD workflow 작성하기 (ref. https://hudi.blog/deploy-with-docker-and-github-actions/)
  - [x] 도메인 연결하기
