### ISSUE TITLE
리스트 생성 시, 색깔 코드를 적용한다. 그리고 상세 조회 시, 색깔 코드를 응답한다.

### ISSUE THREAD

**Issue by kdkdhoho** [8-Sprinters/ListyWave-back#256]
# Description
## 원인
현재 리스트 생성 시, 배경색을 선택하고 서버로 전송한다. 이때 색상의 Hex 값이 전달된다.
하지만 사용자가 이를 악용하여 임의의 값을 보낼 경우 이를 막을 방법이 없다.

## 해결책
따라서, 리스트 생성 시에 미리 정해놓은 `ColorPalette`와 `ColorName`을 서버로 전달한다.
값을 받은 서버는 유효하지 않은 값인 경우 예외를 발생한다. 둘 다 유효한 값인 경우 함께 저장한다.

리스트를 조회하는 여러 API (리스트 상세 조회, 리스트 검색, 리스트 전체 조회)에서는 응답 필드로 `ColorName`을 반환한다. 예외적으로 리스트 상세 조회 API는 `ColorPalette`도 함께 응답한다.

## 주의사항
해당 Issue를 머지하기 전에  _List_ 테이블의 _background_color_ 칼럼에 있는 Hex 값들을 모두 미리 정해놓은 String 값으로 수정해야 한다.
또, _background_palette_ 필드를 추가해야 한다.

# TODO
- [x] 아래 API에 `backgroundColorPalette`와 `backgroundColor`를 모두 입력받고 응답하도록 수정한다.
  - [x] 리스트 생성
  - [x] 리스트 수정
  - [x] 리스트 상세 조회 
    - [x] 입력받을 때, 둘 중 하나라도 유효하지 않은 값이면 예외를 발생한다.
- [x] 아래 API에 `backgroundColor`만 응답하도록 수정한다.
  - [x] 리스트 검색
  - [x] 리스트 전체 조회
- [x] Merge하기 전, _List_ 테이블에 변경 사항 적용하기 !
