### ISSUE TITLE
개발용 로그인 API를 개발한다

### ISSUE THREAD

**Issue by kdkdhoho** [8-Sprinters/ListyWave-back#262]
# 요구 사항
- 프론트엔드가 로컬 환경에서 `dev.api.listywave.com`으로 로그인하면 배포 환경과 동일하게 토큰 정보를 `Set-Cookie`로 받는다.
- 이후 동일한 로컬 환경에서 `dev.api.listywave.com` 으로 요청을 보내도 토큰 정보가 `Cookie`에 담겨 요청된다.

# TODO
- [x] 로컬 로그인용 계정을 메모리에 저장한다.
- [x] 쿼리 파라미터로 인증 정보를 받는 컨트롤러를 구현한다.
- [x] 입력받은 인증 정보가 일치하면 토큰을 생성해 `Set-Cookie`에 담아 응답한다.
  - [x] `Secure`, `httpOnly`, `SameSite = None` 으로 설정한다.

#  Reference
- [kdkdhoho.github.io - HTTP 헤더](https://kdkdhoho.github.io/06-http-header/)
