### ISSUE TITLE
리스트 전체 조회 기능 구현

### ISSUE THREAD

**Issue by kdkdhoho** [8-Sprinters/ListyWave-back#27]
# Description
- 피드 페이지에 사용될 리스트 전체 조회 기능을 커서아이디 페이지네이션 방식으로 구현한다.

# TODO

- [x] 필터링 기능 구현
  - [x] `type`, `category`로 리스트를 필터링할 수 있다.
  - [x] default 값은 다음과 같다.
    - `type`: `my` (required)
    - `category`: `all`

- [x] 일단 1차 MVP에서 해당 정렬 정책
  - [x] default는 `최신순`이다.

# Reference
![와이어프레임](https://github.com/8-Sprinters/ListyWave-back/assets/66300965/3fc721bf-3742-4cc6-8b88-4c606f26208a)

# 관련 Issue
- #26
