### ISSUE TITLE
개발 DB 구축

### ISSUE THREAD

**Issue by kdkdhoho** [8-Sprinters/ListyWave-back#28]
# Description
- 개발 DB를 EC2에 구축합니다.
- DB는 MySQL 8.0+을 사용합니다.

# TODO
- [x] 신규 EC2 생성
- [x] EIP 설정
- [x] 인바운드 규칙 설정
- [x] MySQL 구축
- [x] DEV 계정 생성
  - Host를 EC2 Dev로 지정할 것
