### ISSUE TITLE
리액션 API 추가 및 이에 따른 리스트 상세 조회, 트랜딩 리스트 조회 API 수정

### ISSUE THREAD

**Issue by pparkjs** [8-Sprinters/ListyWave-back#298]
# Description
- 리스트에 대한 3개의 리액션(COOL, AGREE, THANKS)이 추가됨에 따라 리액션 관련 API를 추가( 추후 리액션에 대한 동시성 처리를 진행)
- 리액션이 추가됨에 따라 변경되는 리스트 상세 조회, 트랜딩 리스트 조회 API를 수정한다. 

# TODO
- [x] 리액션하기 API 구현
- [x] 리스트 상세 조회 API 수정
- [x] 트랜딩 리스트  조회 API 수정

# 관련 Issue
- #42
- #279
