### ISSUE TITLE
리스트 삭제 API 구현

### ISSUE THREAD

**Issue by kdkdhoho** [8-Sprinters/ListyWave-back#62]
# TODO
- [x] 리스트 삭제 API 기능 구현
  - [x] 리스트 삭제 시, 관련 데이터도 함께 삭제한다.
    - 관련 데이터: Item, label, image, collaborator, comment, reply
  - [x] Hard Delete 한다.
- [x] 담당자 정해지면 나현님께 noti 드리기

# 관련 Issue
-
