### ISSUE TITLE
Issue Template과 PR Template을 적용한다.

### ISSUE THREAD

**Issue by kdkdhoho** [8-Sprinters/ListyWave-back#7]
# TODO
- [x] Issue Template 적용
- [x] PR Template 적용
- [x] 두 Template 적용법 작성 및 공유
